##############
# Settings for the main Pega to Lego Controller app
##############

robotId: "Gate One" # Bluetooth identification name that is also used in Pega
baseUrl: "https://23.pegatsdemo.com/prweb/api/PegaBotController/1/" # Base url of the controller API
userName: "" # Pega user identifier
password: "" # Pega user identifier
